import jsPDF from 'jspdf';
import { AssessmentData } from '@/types/assessment';

export const generateAssessmentReport = async (data: AssessmentData): Promise<Blob> => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Colors
  const primaryColor = '#4285F4';
  const accentColor = '#34A853';
  
  // Header
  pdf.setFillColor(66, 133, 244);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.text('MaintainX Integration Assessment', 20, 25);
  
  // Reset color
  pdf.setTextColor(0, 0, 0);
  let yPosition = 60;
  
  // Executive Summary
  pdf.setFontSize(18);
  pdf.text('Executive Summary', 20, yPosition);
  yPosition += 15;
  
  pdf.setFontSize(11);
  const summary = [
    `Assessment Mode: ${data.mode === 'quick' ? 'Quick Assessment' : 'Advanced Assessment'}`,
    `Company Size: ${data.company.size}`,
    `Industry: ${data.company.industry}`,
    `Integrations Found: ${data.scorecard.integrationsFound}`,
    `Compatibility: ${data.scorecard.compatibilityPercent}%`,
    `Goals Supported: ${data.scorecard.goalsMatched}`
  ];
  
  summary.forEach(line => {
    pdf.text(line, 20, yPosition);
    yPosition += 8;
  });
  
  yPosition += 10;
  
  // Tech Stack Section
  pdf.setFontSize(16);
  pdf.text('Your Technology Ecosystem', 20, yPosition);
  yPosition += 15;
  
  pdf.setFontSize(11);
  
  // ERP Systems
  if (data.integrations.erp) {
    pdf.setFontSize(12);
    pdf.text('ERP Systems:', 20, yPosition);
    yPosition += 8;
    pdf.setFontSize(10);
    pdf.text(`• ${data.integrations.erp.brand}`, 25, yPosition);
    yPosition += 8;
  }
  
  // Sensors & Monitoring
  if (data.integrations.sensorsMonitoring.length > 0) {
    pdf.setFontSize(12);
    pdf.text('Sensors & Monitoring:', 20, yPosition);
    yPosition += 8;
    data.integrations.sensorsMonitoring.forEach(sensor => {
      if (sensor.brand !== 'None' && sensor.brand !== 'Not sure') {
        pdf.setFontSize(10);
        pdf.text(`• ${sensor.brand} (${sensor.category})`, 25, yPosition);
        yPosition += 6;
      }
    });
    yPosition += 5;
  }
  
  // Automation & SCADA
  if (data.integrations.automationScada.length > 0) {
    pdf.setFontSize(12);
    pdf.text('Automation & SCADA:', 20, yPosition);
    yPosition += 8;
    data.integrations.automationScada.forEach(automation => {
      if (automation.brand !== 'None' && automation.brand !== 'Not sure') {
        pdf.setFontSize(10);
        pdf.text(`• ${automation.brand} (${automation.type})`, 25, yPosition);
        yPosition += 6;
      }
    });
    yPosition += 5;
  }
  
  // Other Systems
  if (data.integrations.otherSystems.length > 0) {
    pdf.setFontSize(12);
    pdf.text('Other Systems:', 20, yPosition);
    yPosition += 8;
    data.integrations.otherSystems.forEach(other => {
      if (other.brand !== 'None' && other.brand !== 'Not sure') {
        pdf.setFontSize(10);
        pdf.text(`• ${other.brand} (${other.type})`, 25, yPosition);
        yPosition += 6;
      }
    });
    yPosition += 5;
  }
  
  // Check if we need a new page
  if (yPosition > pageHeight - 60) {
    pdf.addPage();
    yPosition = 20;
  }
  
  // Goals Section
  yPosition += 10;
  pdf.setFontSize(16);
  pdf.text('Your Maintenance Goals', 20, yPosition);
  yPosition += 15;
  
  data.goals.forEach(goal => {
    pdf.setFontSize(10);
    pdf.text(`• ${goal}`, 25, yPosition);
    yPosition += 6;
  });
  
  // Integration Patterns
  if (data.integrationPatterns.length > 0) {
    yPosition += 15;
    pdf.setFontSize(16);
    pdf.text('Integration Architecture', 20, yPosition);
    yPosition += 15;
    
    data.integrationPatterns.forEach(pattern => {
      pdf.setFontSize(10);
      pdf.text(`${pattern.from} → MaintainX (${pattern.protocol})`, 25, yPosition);
      yPosition += 6;
    });
  }
  
  // Footer
  const footerY = pageHeight - 20;
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by MaintainX Integration Assessment Tool', 20, footerY);
  pdf.text(new Date().toLocaleDateString(), pageWidth - 40, footerY);
  
  return pdf.output('blob');
};
