// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzuftpwiaphvkyxuhgfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dWZ0cHdpYXBodmt5eHVoZ2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTIxNDYsImV4cCI6MjA3MjYyODE0Nn0.z-KEnRM3ECDDqVPJdawtkGMnrKxtMWD7UPpJMC7jW9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});